# Server
server.port=8080

# H2 / JPA
spring.datasource.url=jdbc:postgresql://localhost:5432/sam_library
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=SuperDog!1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable schema.sql initialization
spring.sql.init.mode=never

# Allow CORS origin to be configured
app.cors.allowed-origins=http://localhost:3000
